/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface YtIframe {}
}

declare global {


  interface HTMLYtIframeElement extends Components.YtIframe, HTMLStencilElement {}
  var HTMLYtIframeElement: {
    prototype: HTMLYtIframeElement;
    new (): HTMLYtIframeElement;
  };
  interface HTMLElementTagNameMap {
    'yt-iframe': HTMLYtIframeElement;
  }
}

declare namespace LocalJSX {
  interface YtIframe {}

  interface IntrinsicElements {
    'yt-iframe': YtIframe;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'yt-iframe': LocalJSX.YtIframe & JSXBase.HTMLAttributes<HTMLYtIframeElement>;
    }
  }
}


